### ISSUE TITLE
DST switch March 2020

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#103]
This is a Semi-annual reminder of the upcoming Daylight Saving Time
(DST) change:
     https://www.timeanddate.com/time/dst/2020a.html

Most of the US and Canada will be moving their clocks forward on Sunday,
8 March. This is three weeks earlier than Europe. Most European clocks
will move 1 hour forward on Sunday, 29 March. 

Between 8 March and 29
March, the teleconferences that are scheduled using a UTC clock
will start *one hour later* in local time for most North Americans.

China, Japan and Russia do not observe DST, which means the time
difference between these areas and US/Europe will be one hour less than
it currently is.

For locations that observe DST in Australia and New Zealand, their
clocks will shift back on Sunday, 5 April.

There will be TTWG meetings between the DST switch times on 12th, 19th and 26th March.

Please vote for your preferred choice using 👍 and 👎 on the comments below.

**Comment by nigelmegitt** [comment]
## Option 1: Retain the current UTC time (1600 UTC for 1 hour meetings) on a continuing basis

Non-DST areas: current time, e.g. next day, 0100 in Tokyo.
US: 1 hour later from 12th March onwards, e.g, 0900 start in California instead of 0800.
Europe: 1 hour later from 2nd April, e.g. 1700 UK time, 1800 in Germany

**Comment by nigelmegitt** [comment]
## Option 2: Switch to 1 hour earlier (UTC time) on 2nd April and onwards

Non-DST areas: 1 hour earlier, e.g. next day, 0000 in Tokyo.
US: 1 hour later from 12th March onwards, e.g, 0900 start in California instead of 0800, reverting to previous time from 2nd April onwards.
Europe: current time, e.g. 1600 UK time, 1700 in Germany

**Comment by nigelmegitt** [comment]
## Option 3: Switch to 1 hour earlier (UTC time) on 12th March and onwards

Non-DST areas: Switch to 1 hour earlier (UTC time) on 12th March and onwards
US: current time, e.g, 0800 start in California
Europe: 1 hour earlier from 12th March onwards, e.g. 1500 UK time, 1600 in Germany, reverting to previous time from 2nd April onwards.

**Comment by nigelmegitt** [comment]
Onward actions:
* [ ] Update TTWG homepage - @himorin 
* [ ] Update webex schedule - @nigelmegitt / @plehegar 
* [ ] Send updated joining details - @nigelmegitt 
* [ ] Send Outlook invitations - @nigelmegitt

**Comment by gkatsev** [comment]
The [website](https://www.w3.org/AudioVideo/TT/) says the following, which mostly matches what we decided except for the 2 hour special meetings which start earlier.

> Meetings are held at 1600 UTC (winter time, where it applies) weekly on Thursdays, duration 1 hour. By exception 2 hour meetings may be scheduled, beginning at 1500 UTC. In summer time, meetings begin 1 hour earlier in UTC time.

Should we just say that 2 hour meeting may be scheduled but not mention time? Maybe just not mention any times specifically and say to check the mailing list/agenda issue for accurate times?

**Comment by nigelmegitt** [comment]
> Should we just say that 2 hour meeting may be scheduled but not mention time?

Works for me, though I think setting an expectation is a good thing. If we've just decided that 2 hour meetings will be extended at the end then I'd be happy to say that. For the time being, the situation is unclear because we did not raise the question very explicitly about extending meeting times, but just discussed it briefly in passing, so I'd be happy to a) not mention extended meeting start times for now and b) check in with the group specifically on this question.

**Comment by himorin** [comment]
As pointed, [website](https://www.w3.org/AudioVideo/TT/) says just "Summer time", so we might need to add which DST change we will take. Do we want to add, or just leave as is?
One point I couldn't come up during the call, we may provide ical in wip directory in addition to outlook invitation.

**Comment by nigelmegitt** [comment]
I'm happy to leave the "Summer time" vague on purpose. For a while now I've checked in with the group before every DST change to allow flexibility.

An iCal in the WIP directory is a great idea!

**Comment by himorin** [comment]
> I'm happy to leave the "Summer time" vague on purpose. For a while now I've checked in with the group before every DST change to allow flexibility.

Sure. Then let me have no PR for our website.

> An iCal in the WIP directory is a great idea!

WIP at PR #104 , but help wanted as for now...

**Comment by nigelmegitt** [comment]
This has been overtaken by events, since we can now use the group calendar at https://www.w3.org/groups/wg/timed-text/calendar. Closing.
