### ISSUE TITLE
Incoming liaison from ARIB re IMSC 1.2

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#116]
Liaison received at https://lists.w3.org/Archives/Member/member-tt/2020Apr/0000.html

Opening this issue to track discussion and response.

**Comment by himorin** [comment]
Only found [one example in the past](https://lists.w3.org/Archives/Member/member-tt/2017May/0006.html), and also I've got suggestion as (similar to what was written in an example):

- no formal action is necessity
- add comments into GitHub issue for tracking (as usual discussion and tracking)

should I file issues to imsc repository for the reply?

**Comment by nigelmegitt** [comment]
As discussed on today's call (#111), @himorin or @palemieux to open issues on the w3c/imsc repo for each of the comments raised by ARIB in their liaison, for our discussion prior to writing a liaison message back.

**Comment by nigelmegitt** [comment]
Thank you @himorin for raising the issues on the IMSC repository directly. The next step is for us to discuss those issues before responding back to ARIB.

**Comment by nigelmegitt** [comment]
* [ ] From https://github.com/w3c/imsc/issues/543#issuecomment-635438788, request example of usage of GSUB, PUA, IVS etc to see what the use cases are that apply in Japan.

**Comment by nigelmegitt** [comment]
@mikedo [sent](https://lists.w3.org/Archives/Public/public-tt/2020Jul/0019.html) a link to the English language translation of ARIB STD-B62:

> And the English version of the ARIB spec is here:
> https://www.arib.or.jp/english/std_tr/broadcasting/std-b62.html

**Comment by nigelmegitt** [comment]
Response sent, archived at https://lists.w3.org/Archives/Member/member-tt/2020Sep/0001.html

On the basis that all other actions are now logged as separate issues, I'm closing this.
