### ISSUE TITLE
Arrange joint virtual TPAC meeting with MEIG and Media WG

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#139]

**Comment by himorin** [comment]
- minutes: https://www.w3.org/2020/07/23-tt-minutes.html#t05
- MediaWG: https://www.w3.org/groups/wg/media/participants
- MEIG: https://www.w3.org/groups/ig/me/participants

**Comment by nigelmegitt** [comment]
Email to Chairs of Media WG, MEIG and TTWG sent, asking if the proposed time at https://www.w3.org/wiki/TPAC/2020/GroupMeetings#Joint_Group_meetings_-_Week_of_12-16_October of [2020-10-15 1400 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201014T15&p1=1440) would work.

**Comment by nigelmegitt** [comment]
Agenda for this meeting is at https://www.w3.org/2011/webtv/wiki/TPAC_2020_meeting#Thursday_15_October_2020:_Timed_Text_WG_.2F_Media_WG_.2F_Media_.26_Entertainment_IG_Joint_Meeting

**Comment by himorin** [comment]
@nigelmegitt this seems for TPAC 2020, close this??
