### ISSUE TITLE
Arrange joint virtual TPAC meeting with CSS WG

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#140]

**Comment by himorin** [comment]
- minutes: https://www.w3.org/2020/07/23-tt-minutes.html#t05
- CSS WG: https://www.w3.org/groups/wg/css/participants

**Comment by gkatsev** [comment]
I wrote up a more detailed description of the viewport units issue in WebVTT/Media element here https://github.com/w3c/webvtt/issues/489

**Comment by nigelmegitt** [comment]
Agenda+ w3c/ttml2#1211
