### ISSUE TITLE
Move .travis.yml to GitHub Actions

### ISSUE THREAD

**Issue by himorin** [w3c/ttwg#198]
We need to move PR preview and github.io processing from Travis to GitHub Actions. 

@plehegar raised this issue as tracking.

targets:
- [x] [ttml1](https://github.com/w3c/ttml1/)
- [x] [ttml2](https://github.com/w3c/ttml2/)
- [x] [ttml3](https://github.com/w3c/ttml3/)

reqs, imsc, webvtt is based on respec. webvtt has github actions, others no CI.

**Comment by nigelmegitt** [comment]
If we could make GitHub Actions that do the equivalent of PR preview for the TTML repos that would be a good benefit.

**Comment by plehegar** [comment]
It should be able to.

For example of GitHub action workflows, see
 https://github.com/plehegar/testing/blob/main/.github/workflows/selt_test.yml

If you need, just let me know

**Comment by himorin** [comment]
closing. all PRs merged.
