### ISSUE TITLE
TTWG Meeting 2024-03-14 still 1600 UTC

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#276]
# Agenda

**1. This meeting**
**2. IMSC-HRM**
2.1 AC Review status
**3. DAPT**
3.1 Requests for Wide Review and Horizontal Review
3.2 Issues and pull requests for discussion
**AOB – please notify of any other AOB now!**

### Time and Joining Details: 16:00 - 17:00 (1 hours) UTC

Please be ready for a prompt start at 16:03am UTC time.

Our teleconference is scheduled with reference to UTC Time, the correct time of this teleconference in your locale may change.

Check https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240314T16&p1=1440

See W3C Calendar link for joining details: https://www.w3.org/events/meetings/ea080ceb-16da-4313-a90d-be98a8b17425/20240314T150000/

(if you can't see the joining details and wish to join please contact me)

#### Future meetings and recent activity:

See the [TTWG project board](https://github.com/w3c/ttwg/projects/1) for upcoming meetings.

See individual agenda items for recent activity on specific products.

See the [TTWG home page](https://www.w3.org/AudioVideo/TT/#recent-activity) for links to repositories and recent activity.

___

#### Scribe: 

Previous meeting: https://www.w3.org/2024/02/29-tt-minutes.html

### Prioritise discussion for this meeting and look ahead

Check-point for order of topics and any other business. 

___

### AC Review status

WBS Poll results (may not be visible to all): https://www.w3.org/2002/09/wbs/33280/202402-PR-IMSC-HRM/results

Opportunity to raise any discussion points or updates since previous meeting.

Next steps

* AC Reps to review via WBS poll

So far 1 (editorial) issue raised: https://github.com/w3c/imsc-hrm/issues/79

___

## Agenda+ DAPT

Latest WD (currently 2025-02-01) published at https://www.w3.org/TR/DAPT/ 

### Requests for Wide Review and Horizontal Review

DAPT WR outgoing liaisons complete.

HR requests sent to APA WG, PING, Security, TAG and Internationalisation.

Awaiting responses, from all except PING, Internationalisation and TAG who completed their reviews.

APA WG is likely to approve, and are consulting their members about asking for a change in emphasis of the non-normative text about audio description mixing to promote client-side mixing since it allows more user choice. Potentially we could make such a change anyway.

* [Wide Review outreach log and liaisons list](https://github.com/w3c/dapt/wiki/Wide-Review-outreach-log)

We received [feedback from DVW](https://github.com/w3c/dapt/discussions/187), which has been turned into a Discussion on the DAPT repo; they kindly responded via @cconcolato and the actionable points have been raised as issues.

See https://github.com/w3c/dapt/discussions where the discussions live.

Status update on next steps:

* Address open issues, merge pull requests etc

Since the last meeting:
* [issues closed](https://github.com/w3c/dapt/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+updated%3A%3E2024-02-29): one
* [pull requests closed](https://github.com/w3c/dapt/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+updated%3A%3E2024-02-29): one pull request merged.

### Issues and pull requests for discussion

Issues and pull requests flagged for agenda are at https://github.com/w3c/dapt/labels/agenda - currently 3 issues open

___

**Comment by himorin** [comment]
dup of #275?

**Comment by nigelmegitt** [comment]
> dup of #275?

Thanks, yes. Repurposed for March 14th instead.

**Comment by himorin** [comment]
AOB, please ask your AC rep to submit review on IMSC-HRM PR.
For now, we only have one comment. (with 5 abstains)

**Comment by nigelmegitt** [comment]
No need to AOB that, please raise in §2.1 "AC Review status".

**Comment by cconcolato** [comment]
Regrets for this week. I have conflicting meetings this week.

**Comment by chrisn** [comment]
Regrets also from me today.

**Comment by nigelmegitt** [comment]
Minutes at https://www.w3.org/2024/03/14-tt-minutes.html
