### ISSUE TITLE
TTWG Meeting 2024-02-29 leap year edition

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#277]
# Agenda

**1. This meeting**
**2. IMSC-HRM**
2.1 Transition request to move to PR
**3. DAPT**
3.1 Requests for Wide Review and Horizontal Review
3.2 Issues and pull requests for discussion
**AOB – please notify of any other AOB now!**
AOB.1 Upcoming DST changes

### Time and Joining Details: 15:00 - 16:00 (1 hours) UTC

Please be ready for a prompt start at 15:03am UTC time.

Our teleconference is scheduled with reference to UTC Time, the correct time of this teleconference in your locale may change.

Check https://www.timeanddate.com/worldclock/fixedtime.html?iso=20240229T16&p1=1440

See W3C Calendar link for joining details: https://www.w3.org/events/meetings/ea080ceb-16da-4313-a90d-be98a8b17425/20240229T160000/

(if you can't see the joining details and wish to join please contact me)

#### Future meetings and recent activity:

See the [TTWG project board](https://github.com/w3c/ttwg/projects/1) for upcoming meetings.

See individual agenda items for recent activity on specific products.

See the [TTWG home page](https://www.w3.org/AudioVideo/TT/#recent-activity) for links to repositories and recent activity.

___

#### Scribe: 

Previous meeting: https://www.w3.org/2024/02/15-tt-minutes.html

### Prioritise discussion for this meeting and look ahead

Check-point for order of topics and any other business. 

___

### Transition request to move to PR

https://github.com/w3c/transitions/issues/590 is the transition request issue - the current status is "awaiting publication", hopefully on 2024-02-29.

Between the last meeting and this we did a last-minute CfC to remove the CR exit criteria from the SoTD, which concluded successfully with consensus to make the change, bringing the document into line with common practice in other Proposed Recommendations.

Opportunity to raise any discussion points or updates since previous meeting.

Next steps

* Team will request publication

___

## Agenda+ DAPT

Latest WD (currently 2025-02-15) published at https://www.w3.org/TR/DAPT/ 

### Requests for Wide Review and Horizontal Review

DAPT WR outgoing liaisons complete.

HR requests sent to APA WG, PING, Security, TAG and Internationalisation.

Awaiting responses, from all except PING, Internationalisation and TAG who completed their reviews.

APA WG is likely to approve, and are consulting their members about asking for a change in emphasis of the non-normative text about audio description mixing to promote client-side mixing since it allows more user choice. Potentially we could make such a change anyway.

* [Wide Review outreach log and liaisons list](https://github.com/w3c/dapt/wiki/Wide-Review-outreach-log)

We received [feedback from DVW](https://github.com/w3c/dapt/discussions/187), which has been turned into a Discussion on the DAPT repo; they kindly responded via @cconcolato and the actionable points have been raised as issues.

See https://github.com/w3c/dapt/discussions where the discussions live.

Status update on next steps:

* Address open issues, merge pull requests etc

Since the last meeting:
* [issues closed](https://github.com/w3c/dapt/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+updated%3A%3E2024-02-15): zero
* [pull requests closed](https://github.com/w3c/dapt/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+updated%3A%3E2024-02-15): zero pull requests merged or closed.

### Issues and pull requests for discussion

Issues and pull requests flagged for agenda are at https://github.com/w3c/dapt/labels/agenda

___

## Agenda+ AOB – Upcoming DST changes

See https://www.timeanddate.com/time/dst/2024a.html for a fuller list.

| Place | DST switch date |
|--------|--------|
| North America (mostly) | March 10 DST begins |
| Western Europe (mostly) | March 31 DST begins |
| China, India, Japan | No DST |
| Australia (some of) | April 7 DST ends | 

Our affected upcoming meetings are March 14, March 28, April 11.

| Plan | Action | North America | Western Europe | No DST places |
|--------|--------|--------|--------|--------|
| 1: Track North America | Move UTC time of calls one hour earlier beginning on March 14, and keep at that new UTC time (1500) until DST ends. | Calls' local time remains the same | calls on March 14 and March 28 will be an hour earlier in local time | calls will be one hour earlier from March 14 onwards |
| 2: Track Western Europe | Move UTC time of calls one hour earlier beginning on April 11 and keep at that new UTC time (1500) until DST ends. | calls on March 14 and March 28 will be an hour later in local time | Calls' local time remains the same | calls will be one hour earlier from April 11 onwards |
| 3: Track No DST places | Stay on the current UTC time (1600) | calls will be one hour later from March 14 onwards | calls will be one hour later from April 11 onwards | Calls' local time remains the same | 

We need to choose one of these plans and adjust the calendar.

**Comment by himorin** [comment]
agenda+ DST change at USA from 2024-03-10

**Comment by nigelmegitt** [comment]
Minutes at https://www.w3.org/2024/02/29-tt-minutes.html
