### ISSUE TITLE
Propose new UTC times in March and beyond

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#29]
As discussed in yesterday's call, DST comes in in the US some time before it does in the US.

DST comes in in the US on Sunday 10th March, and in Europe on Sunday 31st March. See this [reference for global switching dates](https://www.timeanddate.com/time/dst/2019a.html) in 2019.

Our current meeting time is 1600 UTC, so over the upcoming period for the locations where most active attendees are located, here are the applicable times on the next few Thursdays.

|Date|**UTC**|USA (CA)|UK|Germany|
|----|-----|----|-----|----|
|<= 7th March|**1600**|0800|1600|1700|
|14 - 28 March: *either*|**1600**|0900|1600|1700|
|*or* 14 - 28 March: |**1500**|0800|1500|1600|
|>= 4 April|**1500**|0800|1600|1700|

The choice we have is when to adopt a 1500 UTC start time, on 14th March onwards or on 4th April onwards.

**Comment by nigelmegitt** [comment]
Add a 👍 to this comment if you would like to switch to 1500 UTC on 14th March.

**Comment by nigelmegitt** [comment]
Add a 👍 to this comment if you would like to switch to 1500 UTC on 4th April.

**Comment by palemieux** [comment]
> Switch to 1500 UTC on 14th March

1600 UTC is more convenient for me on 14-28 March

**Comment by cconcolato** [comment]
I sent regrets for the 14th. I also will be unavailable on the 28th (MPEG Geneva). The only date remaining that matters to me is the 21st. I have a slight preference for 1600 UTC.

**Comment by nigelmegitt** [comment]
Thanks, the outcome is we will switch to 1500 UTC on 4th April. I will send an update to the WG.

**Comment by nigelmegitt** [comment]
Please note that the switch to 1500 UTC has now happened, and applies to 1 hour meetings. For 2 hour meetings as previously agreed we will begin one hour earlier.
