### ISSUE TITLE
TTWG Meeting 2024-09-27 TPAC In person / hybrid all day

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#291]
See also the [TTWG Wiki page for TPAC 2024](https://www.w3.org/wiki/TimedText/tpac2024).

**Comment by cookiecrook** [comment]
Assuming it's not resolved by then, I'd love to get https://github.com/w3c/webvtt/pull/523 merged, or discuss any blocking feedback... This is a PR to resolve issue https://github.com/w3c/webvtt/issues/511

As you're aware, the motivating use case is to enable a new web standard accessibility feature for conveying times of flashing lights common in movies and other streaming video. More detail is explained in https://github.com/w3c/webvtt/issues/512, so so PR 523 is effectively a blocking prerequisite.

**Comment by nigelmegitt** [comment]
Agenda+ @palemieux present considerations for a new edition of IMSC

**Comment by nigelmegitt** [comment]
Agenda+ Run-through of work needed to take TTML2 Second Edition from CR to Rec.

**Comment by nigelmegitt** [comment]
Agenda+ request from @marcoscaceres to present and discuss on improvements to WebVTT Interop testing, 30-45 minutes.

**Comment by gkatsev** [comment]
@cookiecrook hey, we're looking to schedule a slot for WebVTT for Friday afternoon. I was wondering if you had any time constraints on that. Thanks!

**Comment by nigelmegitt** [comment]
@eric-carlson expressed a preference to complete WebVTT items by 3pm when he will need to leave.

**Comment by cookiecrook** [comment]
I can work around Eric's schedule. The following are the times I can be available on Thursday and Friday
- 10:30–lunch Thursday
- 4:00–close Thursday
- 9:00–11:00 Friday 
- Anytime Friday afternoon

**Comment by cookiecrook** [comment]
With @gkatsev’s feedback this week on https://github.com/w3c/webvtt/pull/523, I have enough to work on. Thank you!

Happy to meet Friday if you’d still like to, or I can yield that time. Either is fine with me.

**Comment by nigelmegitt** [comment]
Topics

    DAPT
        Resolving remaining CR must-have issues
        Proposal to request transition to CR
    TTML2 Second Edition
        Editor
        Tasks needed to take it from CR to Rec
        Which version should the "outdated" banner point to in the [January 2020 CR](https://www.w3.org/TR/2020/CR-ttml2-20200128/)?
    IMSC
        Work on a new edition?
    TTML Profile Registry
        Make it into a proper modern-style Registry?
    WebVTT
        Improvements to WebVTT Interop testing
        [w3c/webvtt#253](https://github.com/w3c/webvtt/pull/523) New ATTRIBUTES block
        [w3c/webvtt#512](https://github.com/w3c/webvtt/issues/512) VTT Type Proposal for time-coded general-flash metadata
    DataCue
    Next Generation TextTrackCue
    Joint meeting follow-ups
        M&E IG
        Media WG
        APA WG
    AOB
        Demo slots if time allows


Agenda for today:

* 09:00-09:10 Introductions
* 09:10-09:25 Agenda bash
* 09:30-09:45 Netflix TTAL <--> DAPT demo
* 09:45-10:00 Streamable Text Tracks
* 10:00-10:30 IMSC

10:30-11:00 break

* 11:00-12:30 [Accessible Platform Architectures WG, Timed Text WG, Media and Entertainment IG Joint Meeting](https://www.w3.org/events/meetings/5d9bf691-6f90-45b9-9c2a-b89faaedb191/)

12:30-14:00 lunch

* 14:00-15:00 WebVTT Interop and issues
* 15:00-15:30 DAPT
* 16:00-16:15 TTML2
* 16:15-16:30 TTML Profile Registry
* 16:30-17:00 Joint meeting follow-ups - MEIG, Media WG, APA WG
* 17:00-18:00

**Comment by nigelmegitt** [comment]
Minutes at https://www.w3.org/2024/09/27-tt-minutes.html
