### ISSUE TITLE
Joint TTWG and CSS WG meeting at TPAC 2019

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#52]
## Topics

These topics are collated from the comments on the issue.

* w3c/tt-module-cjk-ext-1#1 (was moved from ttml2 issue 1127)
* w3c/csswg-drafts#2983
* w3c/csswg-drafts#1975
* w3c/csswg-drafts#1974
* w3c/csswg-drafts#1973
* w3c/csswg-drafts#4116
* w3c/csswg-drafts#560
* Question about CSS WG's CR Exit approach when a feature is implemented but only with a vendor prefix

**Comment by palemieux** [comment]
Specification and implementation status of the following TTML-related issues:

* https://github.com/w3c/csswg-drafts/issues/2983
* https://github.com/w3c/csswg-drafts/issues/1975
* https://github.com/w3c/csswg-drafts/issues/1974
* https://github.com/w3c/csswg-drafts/issues/1973

**Comment by nigelmegitt** [comment]
Add to the list:
* w3c/csswg-drafts#4116

**Comment by gkatsev** [comment]
For WebVTT, we had questions whether we could call vendor prefixes as implemented/implementable for the IR. It would be good to get input from the CSS WG in regard to whether a vendor-prefixed property could be considered acceptable.

**Comment by nigelmegitt** [comment]
Also add: 
* w3c/csswg-drafts#560

**Comment by nigelmegitt** [comment]
Closing since this relates to 2019's TPAC joint meeting, which definitely happened.
