### ISSUE TITLE
Request a meeting at TPAC with Chinese IG

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#60]
To discuss the potential requirements for subtitles and captions presented by the Chinese IG.

**Comment by nigelmegitt** [comment]
Danmaku specification (Chinese): https://w3c.github.io/danmaku/
Chinese IG: https://www.w3.org/2018/chinese-web-ig/

Request sent to one of the Chairs: Anqi (Angel) Li (Alibaba) and team contact Fuqiao Xue (chosen because I've met them both before)

**Comment by xfq** [comment]
(Currently incomplete) English translation of the proposal: https://w3c.github.io/danmaku/index_en.html

**Comment by xfq** [comment]
Chinese IG is meeting on Friday afternoon. Here's a link to the (draft) agenda for the Chinese IG F2F:

  https://github.com/w3c/chinese-ig/issues/154

Would it be possible for TTWG to join the Chinese IG meeting on Friday afternoon, given that (IIRC) we requested a larger meeting room? We can also discuss alternatives if that's not possible. Most participants, including one editor of the proposal, Song Xu, will be in Fukuoka for the whole week.

**Comment by nigelmegitt** [comment]
Thank you @xfq , yes, Friday afternoon should be possible I think.

**Comment by xfq** [comment]
Thank you for discussing this.

We added it to the first item on our agenda, on 13:30-14:30. This agenda item will be in English, since it's a joint meeting.

**Comment by nigelmegitt** [comment]
Many thanks @xfq - I'll add that to the TTWG's agenda.

**Comment by nigelmegitt** [comment]
Closing this issue since the request was made and the plan has been made.
