### ISSUE TITLE
Request HR of TTML2

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#75]
As agreed at https://www.w3.org/2019/10/10-tt-minutes.html#x03 request [HR](https://w3c.github.io/charter-timed-text/#coordination) of TTML2:

* [x] accessibility - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0039.html
* [x] internationalization - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0037.html
* [ ] performance 
* [x] privacy - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0038.html
* [x] security - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0038.html
* [x] TAG - w3ctag/design-reviews#432

**Comment by nigelmegitt** [comment]
Performance is listed in the Charter but I cannot action it because https://www.w3.org/Guide/process/charter.html#horizontal-review doesn't guide me to any performance review group. @plehegar please help.

**Comment by nigelmegitt** [comment]
Security and privacy review comments received on 2019-11-07 at https://lists.w3.org/Archives/Public/public-tt/2019Nov/0011.html

**Comment by plehegar** [comment]
(for the record, I responded that performance wasn't needed for TTML2)

**Comment by himorin** [comment]
this issue could be closed since we published target CR by 2020/01/28?

**Comment by nigelmegitt** [comment]
Thanks for the reminder @himorin .
