### ISSUE TITLE
Request HR of IMSC 1.2

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#76]
As agreed at https://www.w3.org/2019/10/10-tt-minutes.html#x03 request [HR](https://w3c.github.io/charter-timed-text/#coordination) of IMSC 1.2:

* [x] accessibility - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0041.html
* [x] internationalization - https://lists.w3.org/Archives/Public/public-tt/2019Oct/0040.html
* [x] privacy - see response from Jeffrey Yaskin at https://lists.w3.org/Archives/Public/public-tt/2019Nov/0011.html also response from Nick Doty at https://lists.w3.org/Archives/Public/public-tt/2020Mar/0013.html and tracked at w3cping/privacy-reviews#2
* [x] security - https://lists.w3.org/Archives/Public/public-web-security/2020Feb/0002.html
* [x] TAG - w3ctag/design-reviews#474
* [ ] ~performance~

**Comment by nigelmegitt** [comment]
Awaiting update on w3c/imsc#503 before proceeding with privacy and security reviews.

**Comment by plehegar** [comment]
I don't think that performance review is relevant for this deliverable. TTML doesn't link to outside resources, so it doesn't enter in the performance timeline. So I suggest you skip.

**Comment by nigelmegitt** [comment]
Message sent to TAG: https://github.com/w3ctag/design-reviews/issues/474#issuecomment-589183157

**Comment by nigelmegitt** [comment]
Message sent to Web Sec: https://lists.w3.org/Archives/Public/public-web-security/2020Feb/0002.html

**Comment by nigelmegitt** [comment]
Message received from PING via Nick Doty https://lists.w3.org/Archives/Public/public-tt/2020Mar/0013.html

**Comment by plehegar** [comment]
May I suggest raise separate issues for the PING comments and add a label "privacy-tracker" on each of them?

**Comment by nigelmegitt** [comment]
Yes you may. I have asked PING to raise them so the provenance is clear but if they come back to me saying they'd rather not then I guess I will have to do it.

**Comment by nigelmegitt** [comment]
Closing since we published IMSC 1.2 Rec
