### ISSUE TITLE
Send information to the group members about rejoining

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#86]
Group members need to rejoin after Charter renewal - @himorin to send email explaining the process.

**Comment by himorin** [comment]
draft (will send out shortly).

--------
  hi all working for timed-text working group,

  The charter of timed-text working group was updated from Nov 28, 2019, all participants of the WG are required to rejoin to the WG within 45 days (by Jan 12, 2020) [1].
  Please (ask to your AC performing action to) join to the TTWG [2] and make you in the timed-text WG, even if you are listed as a member [3]. And also please check your company is listed in group status page [4] after that.

  If something wrong, please just let me know before you struggle on this, like trying to leave from 
the timed-text WG.

  Please note that "list of individuals" page [5] still lists participants in old charter also including you, even before rejoining to the WG.

*1 https://www.w3.org/2003/12/22-pp-faq.html#start
*2 https://www.w3.org/2004/01/pp-impl/34314/join
*3 https://www.w3.org/2000/09/dbwg/details?group=34314
*4 https://www.w3.org/2004/01/pp-impl/34314/status
*5 https://www.w3.org/2000/09/dbwg/details?group=34314&public=1

**Comment by nigelmegitt** [comment]
Sent to https://lists.w3.org/Archives/Public/public-tt/2019Dec/0011.html - this action is complete.
