### ISSUE TITLE
Coordinate with Bullet Chatting TF to find time for a discussion re TTML and WebVTT

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttwg#92]
Need to liaise with @palemieux and @chrisn and Bullet Chatting Task Force to find a suitable date and time.

This follows the presentation to M&E IG that included a gap analysis relative to WebVTT and TTML that made me (for one) think that further assistance from TTWG would be helpful.

**Comment by chrisn** [comment]
Help from TTWG would be very welcome. Discussing with @palemieux today, we'd like to keep the discussion around Bullet Chatting in one place for the time being, so we propose using the M&E IG mailing list for that, and possibly hold additional M&E IG calls - which I hope TTWG members would like to join. Work could then move into TTWG once we've determined the requirements more concretely. Would this approach work for you?

**Comment by himorin** [comment]
@nigelmegitt this seems for TPAC 2020, close this??

**Comment by nigelmegitt** [comment]
Thanks @chrisn and @himorin , I agree.
